name: ulva_model

channels:

  - conda-forge

  - defaults

dependencies:

  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - bottleneck
  - brotli
  - ca-certificates
  - certifi
  - colorama
  - cycler
  - debugpy
  - decorator
  - entrypoints
  - fonttools
  - freetype
  - icc_rt
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - libpng
  - libsodium
  - libtiff
  - libwebp
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nest-asyncio
  - numexpr
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - parso
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pyzmq
  - qt
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - tzdata
  - vc
  - vs2015_runtime
  - wcwidth
  - wheel
  - wincertstore
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:

    - dill
    - et-xmlfile
    - joblib
    - multiprocess
    - openpyxl
    - pathos
    - patsy
    - pox
    - ppft
    - researchpy
    - salib
    - scikit-learn
    - scikit-posthocs
    - sklearn
    - statsmodels
    - threadpoolctl
